services:
  - type: static_site
    name: geo-frontend
    env: node
    rootDir: frontend
    buildCommand: |
      npm install -g npm@10
      npm install --legacy-peer-deps
      npm run build
    publishDir: build
    plan: free
